#!/usr/bin/env bash
#######################################################
## locate: ${XDG_CONFIG_HOME}/herbstluftwm/autostart ##
## author: Vincent (github.com/mother-1)             ##
## detail: startup file for `herbstluftwm'           ##
## notice: edits for version 0.8.0 update            ##
#######################################################

hc() {
    herbstclient "$@"
}

hc emit_hook reload
hc keyunbind --all

Mod=Mod1

tag_names=( I II III IV V )
tag_keys=( {1..5} )

hc set default_frame_layout 2
hc set_layout max

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc attr theme.floating.border_width 3
hc attr theme.floating.outer_width 0
hc attr theme.border_width 3
hc attr theme.inner_width 0
hc attr theme.outer_width 0
hc attr theme.inner_color '#080808'
hc attr theme.active.inner_color '#292929'
hc attr theme.normal.inner_color '#080808'
hc attr theme.outer_color '#292929'
hc attr theme.active.outer_color '#606060'
hc attr theme.normal.outer_color '#080808'
hc attr theme.active.color '#303030'
hc attr theme.normal.color '#202020'
hc attr theme.urgent.color '#FF009A'
hc attr theme.background_color '#101010'

hc set tree_style '·│ ├└+─┐'
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_bg_active_color '#606060'
hc set frame_bg_normal_color '#101010'
hc set frame_border_active_color '#303030'
hc set frame_border_normal_color '#202020'
hc set frame_border_inner_color '#080808'
hc set frame_border_inner_width 0
hc set frame_border_width 4
hc set frame_gap 1
hc set frame_padding 0
hc set frame_transparent_width 0
hc set mouse_recenter_gap 0
hc set smart_frame_surroundings 0
hc set smart_window_surroundings 1
hc set window_gap 1
hc set window_border_active_color '#303030'
hc set window_border_normal_color '#202020'
hc set window_border_urgent_color '#FF009A'

hc unrule -F
hc rule focus=on
hc rule class="mpv" pseudotile=on
hc rule class="Toplevel" pseudotile=on
hc rule class="Dialog" pseudotile=on
hc rule class="sun-awt-X11-XFramePeer" pseudotile=on
hc rule class="forge-view-Main" tag=III
hc rule class="calibre" tag=V
hc rule class~'(.*[iI]ce[cC]at)' tag=IV
hc rule class~'(.*[pP]ale moon)' tag=IV
hc rule class~'(.*[fF]irefox)' tag=IV
hc rule class~'(.*[nN]avigator)' tag=IV
hc rule class~'(.*[tT]ixati)' tag=IV
hc rule class~'(.*[gG]imp)' tag=V
hc rule class~'(.*[gG]color2)' pseudotile=on
hc rule class~'(.*[sS]xiv)' pseudotile=on
hc rule class~'(.*[yY]ad)' pseudotile=on
hc rule title="Open Image" pseudotile=on
hc rule title="Save As" pseudotile=on
hc rule title="Save file" pseudotile=on
hc rule title="Tab Mix Plus Options" pseudotile=on
hc rule title="Loading Tixati..." pseudotile=on
hc rule title="Loading Forge..." pseudotile=on
hc rule title~'(.*Pale Moon.*)' pseudotile=on
hc rule title~'^TLauncher.*' pseudotile=on tag=III
hc rule title~'^TL .*[.*-launcher.*].*' tag=III
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc unlock

panel="${XDG_CONFIG_HOME}/herbstluftwm/panel/dzen-post.zsh"
if [ -x "$panel" ] ; then
    hc emit_hook quit_panel
    for monitor in $(hc list_monitors | cut -d: -f1) ; do
        hc pad 0 45 0 0 0
        exec "$panel" $monitor &
    done
fi
